services:
  # TODO: dns updater
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    environment:
      DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  iperf3-server: #https://registry.hub.docker.com/r/networkstatic/iperf3
    image: networkstatic/iperf3
    container_name: iperf3-server
    command: --server
    ports:
      - 5201:5201
    restart: unless-stopped

